package playbook

// Source: https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html
var taskKeywords = [...]string{
	"action",
	"any_errors_fatal",
	"args",
	"async",
	"become",
	"become_exe",
	"become_flags",
	"become_method",
	"become_user",
	"changed_when",
	"check_mode",
	"collections",
	"connection",
	"debugger",
	"delay",
	"delegate_facts",
	"delegate_to",
	"diff",
	"environment",
	"failed_when",
	"ignore_errors",
	"ignore_unreachable",
	"local_action",
	"loop",
	"loop_control",
	"module_defaults",
	"name",
	"no_log",
	"notify",
	"poll",
	"port",
	"register",
	"remote_user",
	"retries",
	"run_once",
	"tags",
	"throttle",
	"timeout",
	"until",
	"vars",
	"when",
}

// TODO add_internal_fqcns to these strings
var moduleRequireArgs = [...]string{
	"command",
	"win_command",
	"ansible.windows.win_command",
	"shell",
	"win_shell",
	"ansible.windows.win_shell",
	"raw",
	"script",
}
