# playbook.yaml
- hosts: all
  tasks:
    - name: Ensure group "somegroup" exists
      group:
        name: somegroup
        state: present

    - name: Ensure group "docker" exists with correct gid
      group:
        name: docker
        state: present
        gid: 1750

    - name: Ensure group "group_to_del" exists
      group:
        name: group_to_del
        state: present

    - name: Ensure group "group_to_del" doesn't exist
      group:
        name: group_to_del
        state: absent