// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: remote/proto/gosible.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleName string    `protobuf:"bytes,1,opt,name=moduleName,proto3" json:"moduleName,omitempty"`
	VarsJson   []byte    `protobuf:"bytes,2,opt,name=varsJson,proto3" json:"varsJson,omitempty"`
	MetaArgs   *MetaArgs `protobuf:"bytes,3,opt,name=metaArgs,proto3" json:"metaArgs,omitempty"`
}

func (x *ExecuteModuleRequest) Reset() {
	*x = ExecuteModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_gosible_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteModuleRequest) ProtoMessage() {}

func (x *ExecuteModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_gosible_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteModuleRequest.ProtoReflect.Descriptor instead.
func (*ExecuteModuleRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_gosible_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteModuleRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ExecuteModuleRequest) GetVarsJson() []byte {
	if x != nil {
		return x.VarsJson
	}
	return nil
}

func (x *ExecuteModuleRequest) GetMetaArgs() *MetaArgs {
	if x != nil {
		return x.MetaArgs
	}
	return nil
}

type ExecuteModuleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReturnValueJson []byte `protobuf:"bytes,1,opt,name=returnValueJson,proto3" json:"returnValueJson,omitempty"`
}

func (x *ExecuteModuleReply) Reset() {
	*x = ExecuteModuleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_gosible_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteModuleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteModuleReply) ProtoMessage() {}

func (x *ExecuteModuleReply) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_gosible_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteModuleReply.ProtoReflect.Descriptor instead.
func (*ExecuteModuleReply) Descriptor() ([]byte, []int) {
	return file_remote_proto_gosible_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteModuleReply) GetReturnValueJson() []byte {
	if x != nil {
		return x.ReturnValueJson
	}
	return nil
}

type MetaArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PythonInterpreter string `protobuf:"bytes,1,opt,name=pythonInterpreter,proto3" json:"pythonInterpreter,omitempty"`
	PyRuntimeZipData  []byte `protobuf:"bytes,2,opt,name=pyRuntimeZipData,proto3" json:"pyRuntimeZipData,omitempty"`
}

func (x *MetaArgs) Reset() {
	*x = MetaArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_proto_gosible_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaArgs) ProtoMessage() {}

func (x *MetaArgs) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_gosible_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaArgs.ProtoReflect.Descriptor instead.
func (*MetaArgs) Descriptor() ([]byte, []int) {
	return file_remote_proto_gosible_proto_rawDescGZIP(), []int{2}
}

func (x *MetaArgs) GetPythonInterpreter() string {
	if x != nil {
		return x.PythonInterpreter
	}
	return ""
}

func (x *MetaArgs) GetPyRuntimeZipData() []byte {
	if x != nil {
		return x.PyRuntimeZipData
	}
	return nil
}

var File_remote_proto_gosible_proto protoreflect.FileDescriptor

var file_remote_proto_gosible_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x67, 0x6f,
	0x73, 0x69, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x14,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x73, 0x4a, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x76, 0x61, 0x72, 0x73, 0x4a, 0x73, 0x6f, 0x6e,
	0x12, 0x33, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x41, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x41, 0x72, 0x67, 0x73, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x41, 0x72, 0x67, 0x73, 0x22, 0x3e, 0x0a, 0x12, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x64, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x41, 0x72, 0x67,
	0x73, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x79,
	0x74, 0x68, 0x6f, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x2a, 0x0a, 0x10, 0x70, 0x79, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5a, 0x69, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x70, 0x79, 0x52, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x5a, 0x69, 0x70, 0x44, 0x61, 0x74, 0x61, 0x32, 0x6a, 0x0a, 0x0d, 0x47,
	0x6f, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x59, 0x0a, 0x0d,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x23, 0x2e,
	0x67, 0x6f, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x6f, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x63, 0x79, 0x6c, 0x6c, 0x61, 0x64, 0x62, 0x2f, 0x67,
	0x6f, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_remote_proto_gosible_proto_rawDescOnce sync.Once
	file_remote_proto_gosible_proto_rawDescData = file_remote_proto_gosible_proto_rawDesc
)

func file_remote_proto_gosible_proto_rawDescGZIP() []byte {
	file_remote_proto_gosible_proto_rawDescOnce.Do(func() {
		file_remote_proto_gosible_proto_rawDescData = protoimpl.X.CompressGZIP(file_remote_proto_gosible_proto_rawDescData)
	})
	return file_remote_proto_gosible_proto_rawDescData
}

var file_remote_proto_gosible_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_remote_proto_gosible_proto_goTypes = []interface{}{
	(*ExecuteModuleRequest)(nil), // 0: gosible.proto.ExecuteModuleRequest
	(*ExecuteModuleReply)(nil),   // 1: gosible.proto.ExecuteModuleReply
	(*MetaArgs)(nil),             // 2: gosible.proto.MetaArgs
}
var file_remote_proto_gosible_proto_depIdxs = []int32{
	2, // 0: gosible.proto.ExecuteModuleRequest.metaArgs:type_name -> gosible.proto.MetaArgs
	0, // 1: gosible.proto.GosibleClient.ExecuteModule:input_type -> gosible.proto.ExecuteModuleRequest
	1, // 2: gosible.proto.GosibleClient.ExecuteModule:output_type -> gosible.proto.ExecuteModuleReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_remote_proto_gosible_proto_init() }
func file_remote_proto_gosible_proto_init() {
	if File_remote_proto_gosible_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_remote_proto_gosible_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_gosible_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteModuleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_proto_gosible_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_remote_proto_gosible_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remote_proto_gosible_proto_goTypes,
		DependencyIndexes: file_remote_proto_gosible_proto_depIdxs,
		MessageInfos:      file_remote_proto_gosible_proto_msgTypes,
	}.Build()
	File_remote_proto_gosible_proto = out.File
	file_remote_proto_gosible_proto_rawDesc = nil
	file_remote_proto_gosible_proto_goTypes = nil
	file_remote_proto_gosible_proto_depIdxs = nil
}
