name: |
  [AWS] Reboot Instance

on:
  workflow_dispatch:
    inputs:
      ip_address:
        description: The IPv4 address of the instance
        required:    true
        type:        string
      region:
        description: The IPv4 address of the instance
        required:    true
        type:        string
        default:     us-east-1

jobs:
  reboot-instance:
    runs-on:     ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region:            ${{ github.event.inputs.region }}
          role-to-assume:        ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: "900"
          mask-aws-account-id:   "false"
      - name: Verify AWS credentials
        run: |
          aws sts get-caller-identity
      - name: Reboot instance
        run: |
          aws ec2 describe-instances --region "${{ github.event.inputs.region }}" --filters "Name=ip-address,Values=${{ github.event.inputs.ip_address }}" "Name=tag:Project,Values=gosible" --query 'Reservations[*].Instances[*].InstanceId' --output text | while read -r id; do
            echo "# Rebooting instance $id ..."
            aws ec2 reboot-instances --region "${{ github.event.inputs.region }}" --instance-ids "$id"
          done
